# Chance is the chance that a mob will not be infernal, the lower the number the higher the chance. (min 1)
# Enabledworlds are the worlds that infernal mobs can spawn in.
# Enabledmobs are the mobs that can become infernal.
# Loot is the items that are dropped when an infernal mob dies. (You can have up to 64)
# Item is the item, Amount is the amount, Durability is how damaged it will be (0 is undamaged).
# nameTagsLevel is the visibility level of the name tags, 0 = no tag, 
# 1 = tag shown when your looking at the mob, 2 = tag always shown.
# Note, if you have name tags set to 0, on server restart all infernal mobs will turn normal.
# If you want to enable the boss bar you must have BarAPI on your server.
# nameTagsName and bossBarsName have these special tags: <mobLevel> = the amount of powers the boss has.
# <abilities> = A list of about 3-5 (whatever can fit) names of abilities the boss has.
# <mobName> = Name of the mob, so if the mob is a creeper the mobName will be "Creeper".
configVersion: 'git-Spigot-b5a13e6-0d8350a (MC: 1.16.2)'
chance: 70
namePrefix: '&4&lBOSS'
nameTagsLevel: 1
nameTagsName: '&4&l<prefix> &c<mobName>'
bossBarsName: '&fNivel &4<mobLevel> &4&l<prefix> &c<mobName>'
enableBossBar: true
bossBarSettings:
  defaultColor: RED
  defaultStyle: SOLID
enableScoreBoard: false
showHealthOnScoreBoard: true
effectAllPlayerAttacks: true
enableParticles: true
enableDeathMessages: false
deathMessages:
- '&cplayer &chas killed an mob&c!'
- '&cAn mob &cwas slain by player&c!'
- '&cplayer &cowned an mob&c!'
- '&cAn mob &cwas beheaded by player&c''s weapon!'
- '&cplayer&c''s weapon &ckilled an mob&c!'
- '&cAn mob &cwas killed by player &cusing a weapon&c!'
enableSpawnMessages: false
spawnMessageRadius: 200
spawnMessages:
- '&c¡APARECIO UN &4&LBOSS. &cEncuentralo! &7¿&cPodras contra el&7'

mobworlds:
- <all>
effectworlds:
- <all>
enabledmobs:
- ELDER_GUARDIAN
- WITHER_SKELETON
- STRAY
- HUSK
- ZOMBIE_VILLAGER
- SKELETON_HORSE
- ZOMBIE_HORSE
- EVOKER
- VEX
- VINDICATOR
- CREEPER
- SKELETON
- SPIDER
- GIANT
- ZOMBIE
- SLIME
- PIG_ZOMBIE
- ENDERMAN
- CAVE_SPIDER
- SILVERFISH
- BLAZE
- MAGMA_CUBE
- BAT
- WITCH
- ENDERMITE
- GUARDIAN
- SHULKER
- ILLUSIONER
- LLAMA
- DROWNED
- PHANTOM
- PUFFERFISH
enabledCharmSlots:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 40
- 36
- 37
- 38
- 39
poisonous: true
armoured: true
blinding: true
withering: true
tosser: true
thief: true
quicksand: true
bullwark: true
rust: true
sapper: true
1up: true
cloaked: true
ender: true
ghastly: true
lifesteal: true
sprint: true
storm: true
webber: true
vengeance: true
weakness: true
berserk: true
explode: true
potions: true
mama: true
molten: true
archer: true
necromancer: true
firework: true
gravity: true
flying: true
mounted: true
morph: true
ghost: true
confusing: true
mamaSpawnAmount: 5
vengeanceDamage: 6
berserkDamage: 6
moltenBurnLength: 5
gravityLevitateLength: 8
horseMountsHaveSaddles: true
armouredMountsHaveArmour: true
fireworkColour:
  red: 255
  green: 10
  blue: 10
enabledSpawnReasons:
- BREEDING
- BUILD_WITHER
- CHUNK_GEN
- CUSTOM
- DEFAULT
- INFECTION
- SPAWNER_EGG
- LIGHTNING
- NATURAL
- NETHER_PORTAL
- OCELOT_BABY
- REINFORCEMENTS
- SILVERFISH_BLOCK
- SLIME_SPLIT
mobParticles:
- lavaSpark:1:10
mountFate: nothing
enabledMounts:
- SPIDER
- SKELETON_HORSE
- ZOMBIE_HORSE
- DONKEY
- MULE
- SLIME
- GHAST
- MAGMA_CUBE
- ENDER_DRAGON
- BAT
- PIG
- SHEEP
- COW
- CHICKEN
- MUSHROOM_COW
- HORSE
- POLAR_BEAR
- LLAMA
- PHANTOM
enabledRiders:
- WITHER_SKELETON
- STRAY
- HUSK
- ZOMBIE_VILLAGER
- EVOKER
- VINDICATOR
- SKELETON
- ZOMBIE
- PIG_ZOMBIE
- ENDERMAN
- WITCH
- SNOWMAN
- VILLAGER
- ILLUSIONER
- DROWNED
disabledBabyMobs:
- WOLF
- MUSHROOM_COW
- COW
- SHEEP
- PIG
- CHICKEN
- OCELOT
- HORSE
minpowers: 5
maxpowers: 9
healthMultiplier: 4
healthByPower: false
healthByDistance: false
powerByDistance: false
healthToAdd: 5
powerToAdd: 1
xpMultiplier: 8
addDistance: 200
enableDrops: true
dropChance: 5
enableFarmingDrops: false
naturalSpawnHeight: 0
